DROP TABLE IF EXISTS incoming_document;

create table incoming_document
(
    id              bigint generated by default as identity
        primary key,
    reg_number      varchar(255) not null,
    reg_date        date         not null,
    out_doc_number  varchar(255),
    out_doc_date    date,
    delivery_method varchar(255),
    correspondent   varchar(255) not null,
    subject         varchar(100) not null,
    description     varchar(1000),
    due_date        date,
    access          boolean      not null,
    control         boolean      not null,
    file_upload     varchar(255)
);

alter table incoming_document
    owner to postgres;
